### ISSUE TITLE
List of Python 3 compatible packages isn't complete

### ISSUE THREAD

**Issue by pydanny** [pydanny/djangopackages#276]
https://www.djangopackages.com/python3/

It's missing a lot of packages. For example, dj-libcloud.

**Comment by adamchainz** [comment]
Also `django-mysql` - was just checking if it appeared there. And every release has supported Python 3: https://www.djangopackages.com/packages/p/django-mysql/ :cry:

**Comment by pydanny** [comment]
Sorry. I'll see what I can do about fixing this ASAP.
