### ISSUE TITLE
https://djangopackages.com doesn't work (missing a redirect on the webserver)

### ISSUE THREAD

**Issue by santagada** [pydanny/djangopackages#307]
http://djangopackages.com redirects to https://www.djangopackages.com but using https doesn't work. I would redirect all variations to https://djangopackages.com but at least it should redirect to the www site.

**Comment by ulgens** [comment]
It's still not working :(

**Comment by pydanny** [comment]
Can you try it now? We just fixed all the DNS stuff.

**Comment by ulgens** [comment]
It's working now, thanks! :)

**Comment by pydanny** [comment]
Yay! 🚀
