### ISSUE TITLE
Duplicate grid entries allowed

### ISSUE THREAD

**Issue by tomchristie** [pydanny/djangopackages#311]
Eg this package https://www.djangopackages.com/packages/p/django-rest-assured/ appears twice in the REST framework grid, and cannot be rectified.

---

Project detail:

![screen shot 2015-01-07 at 15 15 15](https://cloud.githubusercontent.com/assets/647359/5647672/005e8f4c-9680-11e4-9188-bcbb00fb7c7e.png)

---

Grid display:

![screen shot 2015-01-07 at 15 16 42](https://cloud.githubusercontent.com/assets/647359/5647695/4097b570-9680-11e4-9e72-85d2869914e5.png)

**Comment by tomchristie** [comment]
Also thank you so much for Django packages - super wonderful & really happy to see it now linked from the docs proper, as it should be :)

**Comment by pydanny** [comment]
Fixed!

We're delighted it's useful to you. FWIW, in the very near future we plan to migrate to using Django REST Framework for the API. How cool is that?

**Comment by tomchristie** [comment]
> in the very near future we plan to migrate to using Django REST Framework for the API. How cool is that?

Fab. :) I'd better reciprocate, and use the API to include the list of REST framework packages directly on one of the docs pages.
