### ISSUE TITLE
Information outdated for some commits in github.

### ISSUE THREAD

**Issue by xpostudio4** [pydanny/djangopackages#312]
In both Oscar and cartridge the information of the last commit is outdated.
**Note: I noticed that the original url of oscar was https://github.com/tangentlabs/django-oscar and the actual is https://github.com/django-oscar/django-oscar. Cartridge case is different.

![screen shot 2015-02-22 at 5 58 08 pm](https://cloud.githubusercontent.com/assets/755375/6320752/c25e5a04-babc-11e4-9107-47ee567249d5.png)

**Comment by pydanny** [comment]
I went to the edit link, which arguably isn't bright enough to see, and fixed it. :wink: 

![edit-link](https://cloud.githubusercontent.com/assets/62857/6321150/3067ca5e-baa8-11e4-8a6d-7e79d7c429c1.png)
