### ISSUE TITLE
ssl certificate has expired

### ISSUE THREAD

**Issue by santagada** [pydanny/djangopackages#313]
Found a twit about is, will leave open so other people don't re-create it:
https://twitter.com/pydanny/status/574005015188226048

**Comment by santagada** [comment]
Found a twit about is, will leave open so other people don't re-create it.

**Comment by pydanny** [comment]
Thanks!

**Comment by pydanny** [comment]
We've been trying to resolve it since Friday:

https://twitter.com/pydanny/status/575056311479574528
https://twitter.com/pydanny/status/575055875842424833

**Comment by pydanny** [comment]
Resolved and documented in c4ea735bde9f1c390953e823e43c1a20e48ec0a9.
