### ISSUE TITLE
Unable to "Sign in with Github"

### ISSUE THREAD

**Issue by kbytesys** [pydanny/djangopackages#324]
When I try to sign in, I get a generic error:

"If this seems like a bug, would you please do us a favor and create a ticket?"

(Server error 500)

**Comment by pydanny** [comment]
Is this your first attempt to sign in or do you have an existing account under a different username?

**Comment by pydanny** [comment]
Can you try again? I uploaded a patch.

**Comment by pydanny** [comment]
Nevermind, the patch broke the site.

**Comment by arocks** [comment]
I get the same error. It is my first attempt at signing up.

**Comment by pydanny** [comment]
Ack, rolling back to Django 1.7.9 isn't going to be easy. Seems like this is the final reason to move the site to django-allauth. I'll have to find time to do it. I'm on vacation this week but I'll try to get it done.

**Comment by kbytesys** [comment]
django-allauth is a good choice. Take your time and good work :+1:

**Comment by pydanny** [comment]
Please test again! I think I fixed it by running this:

```python manage.py migrate auth
Operations to perform:
  Apply all migrations: auth
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
~ $ exit
```

**Comment by kbytesys** [comment]
Ok. It works.

**Comment by arocks** [comment]
Logged in. Thanks!
