### ISSUE TITLE
Dockerize Django Packages

### ISSUE THREAD

**Issue by pydanny** [pydanny/djangopackages#326]

**Comment by jayfk** [comment]
What are the main pain points right now? I'm currently porting a lot of projects to the new V2 Compose format that brings a lot of goodies.

With native networking support there's now a chance to get (somewhat faked) zero downtime deployments using haproxy in front of nginx. The idea is to let haproxy buffer requests when the stack restarts.

**Comment by pydanny** [comment]
Moving this to Gitter.
