### ISSUE TITLE
Please link to the latest version on readthedocs

### ISSUE THREAD

**Issue by guettli** [pydanny/djangopackages#329]
On the package-view page the link to "readthedocs" links to a ugly page where you need to choose the version you want to see. Please link to the latest docs instead.

example:
This page https://www.djangopackages.com/packages/p/django-sitetree/
links to that: https://readthedocs.org/projects/django-sitetree/

Please choose a default. Either "stable" or "latest". Both are better then the current choose-version-page.

**Comment by pydanny** [comment]
1. Whoever added that repo specified that particular address.
2. Whoever views that page who is authenticated can change that value. 

Django Packages has absolutely nothing to do with choosing which page is chosen for the documentation link. 

If you feel this should be changed, click on the '+' Icon and point the documentation link to the target you feel is appropriate.
<img width="609" alt="screen shot 2015-10-12 at 5 29 06 pm" src="https://cloud.githubusercontent.com/assets/62857/10501700/e72f6c58-7298-11e5-815e-5621a9f9145b.png">

**Comment by guettli** [comment]
Thank you. I was not aware that anybody can change it. I updated this one and will the next ones which link to the "choose docs version" page.
