### ISSUE TITLE
Renaming of a package gives strange results

### ISSUE THREAD

**Issue by jobec** [pydanny/djangopackages#335]
I recently added a package and then renamed it because the name was to complex.
For some reason the old name is still showing when searching but the link doesn't resolve anymore.
Also, after renaming, it's showing versions from pypi that don't exist.

The new name:
https://www.djangopackages.com/packages/p/django-auth-adfs/
The old name:
https://www.djangopackages.com/packages/p/django-auth-adfs3-oauth2/

**Comment by jobec** [comment]
Eventually it resolved itself.

**Comment by pydanny** [comment]
Apologies for the slow response. Overwhelmed by non-fun stuff. 

Anyway, what you encountered was a caching refresh issue. :disappointed:
