### ISSUE TITLE
Github Login Broken

### ISSUE THREAD

**Issue by raonyguimaraes** [pydanny/djangopackages#338]
Hello I tried to login using my github account and I received the following error:

![selection_034](https://cloud.githubusercontent.com/assets/124987/15214647/837f4af0-184e-11e6-926f-a53280cf5fc3.png)

Here is the broken url:

https://www.djangopackages.com/auth/complete/github/?code=ca16e9fa5fe481b2979c&redirect_state=8jKfVXJNSPrs7h9ICQYidEByYK2F3pgz&state=8jKfVXJNSPrs7h9ICQYidEByYK2F3pgz

**Comment by pydanny** [comment]
Hi @raonyguimaraes, it's a database issue that I think I just fixed. Please try again.

**Comment by raonyguimaraes** [comment]
Hi Daniel,

Sorry, not yet. I usually have problems with login because of my big name: "Raony Guimarães Corrêa Do Carmo Lisboa Cardenas"

Not sure if that's the case in here, but if this is only me I bet it is ... :smile: 

I'm sure I did successfully login in the past. 

https://www.djangopackages.com/auth/complete/github/?code=aed9ba3833140297bb7b&redirect_state=bwjm4ymNLOpWVlaylVb9HafgS6b61Thj&state=bwjm4ymNLOpWVlaylVb9HafgS6b61Thj

**Comment by pydanny** [comment]
Can you try now?

**Comment by raonyguimaraes** [comment]
HI Daniel, sorry not yet. This bug is going on forever... I will take a
look at your code.

**Comment by pydanny** [comment]
We just moved to a new server and made some configuration changes, I hoped that would have fixed the problem.  That said, our OAuth is really old a crusty, in need of an upgrade. I hope to be able to visit this in the next week or so. Sorry about the delay. 😞

**Comment by raonyguimaraes** [comment]
Hi Daniel, I just discovered the problem was all the way upstream to Django:

https://github.com/django/django/blob/master/django/contrib/auth/models.py#L320
last_name = models.CharField(_('last name'), max_length=30, blank=True)

My last_name is bigger than 30 characters... :disappointed:

I will report the bug in there. I changed my name on Github and that solved the problem with djangopackages. I can now login!

So thank you for all the help and support!

**Comment by raonyguimaraes** [comment]
Hi pydanny/djangopackag,

I'd like to add you to my professional network on LinkedIn.

- Raony

Confirm that you know Raony: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=oZCvj2bo&invitationId=6197095145255559169&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiur6y71p%7En3








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iur6y71p-n3&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGCF6sUEs_hTQAAAVgCBdfeS2HkzUGJcLIauvNjOibj7qyNQxML1rJrH1GTNVDV05BGI38fT9zdSdFwMLSH20uQyqMaXuG-w5L4mjJanRl4QbJshhktOJKjRbGZ8H508E4QZA7VWvEo_klm371jfBW4xA0-zfHhjg0zuKOU6mnS_LrQIxCz5I9OVCMJYBOHcJAq&eid=0-iur6y71p-n3


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iur6y71p-n3&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jayfk** [comment]
**WTF**

**Comment by pydanny** [comment]
**ROFL**

**Comment by raonyguimaraes** [comment]
Raony Guimarães would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=oZCvj2bo&invitationId=6197095145255559169&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-rlw5uf%7Eiv14yljg%7Eav

View Raony Guimarães&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=oZCvj2bo&invitationId=6197095145255559169&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-rlw5uf%7Eiv14yljg%7Eav





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=rlw5uf-iv14yljg-av&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=rlw5uf-iv14yljg-av&loid=AQEF0SZcCilhMQAAAVgmbVgq6UDDPhS3X3yEeQyXPuHpP-88zh4WHssXGz3151Zql1jYjhGKvfQyHpPLjgCENv89YXQzImMTETs5gqA20M4q8I_dFT89wtfbMi9wCDyMQymsyaTIeKT2rtHyAbxLH2TteDVnbS6V8B4xhjibxfrpz0ScMd3IhfWEAAbYbbN7WN44

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=rlw5uf-iv14yljg-av&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by raonyguimaraes** [comment]
Hi ,

Raony Guimarães would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=oZCvj2bo&invitationId=6197095145255559169&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-rlw5uf%7Eivazcn4w%7Euu

View Raony Guimarães&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=oZCvj2bo&invitationId=6197095145255559169&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-rlw5uf%7Eivazcn4w%7Euu





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=rlw5uf-ivazcn4w-uu&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=rlw5uf-ivazcn4w-uu&loid=AQEyvf9jlNUNNQAAAVhKfbEWhR6fO2zAVdxw90ltoumC29WcTs5rBOmKnaA27591XAwODDoh0NOf4CWqUSd_YgFJiIqBEkOlaIA99vULvBSwkm90OO9IqaHFQhUXqFKSp5p7nS6smSLMf7Ithlao-bjog8kiNIrD43I1VoAqaGzU67yDRUY9kJA4Byk6MKiX8q9l

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=rlw5uf-ivazcn4w-uu&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
