### ISSUE TITLE
Django template tags shown in results

### ISSUE THREAD

**Issue by Nuruddinjr** [pydanny/djangopackages#352]
![image](https://cloud.githubusercontent.com/assets/9083431/19879975/8841e2e2-a01a-11e6-8519-d545db5195e9.png)

**Comment by pydanny** [comment]
I can't replicate this error. What search term did you use?

**Comment by Nuruddinjr** [comment]
https://djangopackages.org/grids/g/seo/

**Comment by pydanny** [comment]
Weird. Still not seeing it. Which browser are you using?

**Comment by Nuruddinjr** [comment]
Google Chrome

**Comment by Nuruddinjr** [comment]
Oh they disappeared from my results too =)
