### ISSUE TITLE
Cannot add package - I get an error telling me to report an issue

### ISSUE THREAD

**Issue by pkrzyzaniak** [pydanny/djangopackages#373]
Here is a package I want to add:
https://github.com/ArabellaTech/drf_tweaks (as "Other")

**Comment by pydanny** [comment]
I've confirmed that this is indeed a bug. We'll look into it tomorrow.

**Comment by rajanmandanka** [comment]
I am not able to upload my admin package.

https://github.com/rajanmandanka/pyadmin
![screenshot](https://cloud.githubusercontent.com/assets/24405314/20919276/f16d53fc-bbc0-11e6-97d4-536a9be6fc23.png)

**Comment by pydanny** [comment]
I'm just starting again to work with the Django Software Foundation (DSF) to transfer the project to their ownership. 

In the meantime, please do not add any more "Me too's" or "Still doesn't work" comments. I know this is the case, and all related tickets will be addressed and closed in due time.

**Comment by jayfk** [comment]
Fixed in https://github.com/pydanny/djangopackages/commit/86861a444dfc06629b7119c5504679e7197f04b9 and backported to the "old" server.
