### ISSUE TITLE
Error when adding a package - Error page seems to be broken too.

### ISSUE THREAD

**Issue by jeremygaul** [pydanny/djangopackages#374]
When submitting the package 

https://github.com/jeremygaul/django-gallery 

I get an error on submission, tried in chrome and safari.  Page seems to be partial and has a broken image.

<img width="1431" alt="screenshot 2016-11-11 03 10 21" src="https://cloud.githubusercontent.com/assets/2946941/20213257/950dc8de-a7bc-11e6-897f-499a7ece85d6.png">

**Comment by asfaltboy** [comment]
Same here, attached below is .har file of the 500 error:

[djangopackages.org.har.zip](https://github.com/pydanny/djangopackages/files/587414/djangopackages.org.har.zip)

**Comment by pydanny** [comment]
I'm just starting again to work with the Django Software Foundation (DSF) to transfer the project to their ownership. 

In the meantime, please do not add any more "Me too's" or "Still doesn't work" comments. I know this is the case, and all related tickets will be addressed and closed in due time.
