### ISSUE TITLE
Replace django-coverage

### ISSUE THREAD

**Issue by jayfk** [pydanny/djangopackages#378]
.. as it is not compatible with Python 3.

**Comment by andriisoldatenko** [comment]
@jayfk can you please update description and add link to library which need porting to Python3.

**Comment by jayfk** [comment]
@andriisoldatenko django coverage, see: https://bitbucket.org/kmike/django-coverage/issues/18/fails-to-run-when-installed-from-pip-in

**Comment by jayfk** [comment]
Removed in https://github.com/pydanny/djangopackages/commit/5e65dd881b8827ad40aa6489f60a45973fc4c4a1
