### ISSUE TITLE
Multiple errors on package and profile adding and editing

### ISSUE THREAD

**Issue by aleksihakli** [pydanny/djangopackages#401]
Reported in #372, #373 and #374, the profile edit page also errors when a BitBucket username is added to a just-signed-in GitHub account.

I first signed in to the service, then tried to edit my profile which gave a ISE 500. 

After the profile edit problem I shrugged and went on to add a package to a grid, which gave the same broken ISE 500 page.

**Comment by aleksihakli** [comment]
I think the page errors on just about everything at the moment. Editing a grid page also produces an error as well as URL changes, in #404.

**Comment by pydanny** [comment]
I'm just starting again to work with the Django Software Foundation (DSF) to transfer this project to their ownership. 

In the meantime, please do not add any more "Me too's" or "Still doesn't work" comments. I know this is the case, and all related tickets will be addressed and closed in due time.
