### ISSUE TITLE
Editing Repo URL leads to failure

### ISSUE THREAD

**Issue by nijel** [pydanny/djangopackages#403]
When trying to change Repo URL, the operation fails:

![django_packages_a_directory_of_reusable_apps _sites _tools _and_more_for_your_django_projects _-_2016-12-14_17 51 42](https://cloud.githubusercontent.com/assets/212189/21191629/076d01dc-c226-11e6-8af4-922b6ed04ab9.png)

I wanted to edit https://djangopackages.org/packages/p/weblate/ as the repository has been moved to https://github.com/WeblateOrg/weblate/

**Comment by jayfk** [comment]
Fixed in 86861a4 and backported to the "old" server. I've also added the new URL.
