### ISSUE TITLE
Error upon adding package

### ISSUE THREAD

**Issue by iMakedonsky** [pydanny/djangopackages#407]
Tried to add my package to djangopackages, but got error
![error](https://cloud.githubusercontent.com/assets/13186918/21538426/a84526b8-cda5-11e6-9779-524e598b6fdd.jpg)

**Comment by iMakedonsky** [comment]
link to pacakge: https://github.com/iMakedonsky/drf-autodocs

**Comment by fladi** [comment]
Had the same issue right now when I tried to add my package: https://github.com/fladi/django-static-push

**Comment by andriisoldatenko** [comment]
+1
https://djangopackages.org/packages/add/
Try to add https://github.com/elbuo8/sendgrid-django
@pydanny  any ideas? Do you need help to fix it?

**Comment by andriisoldatenko** [comment]
Possible duplicates:
- pydanny/djangopackages/issues/401
- pydanny/djangopackages/issues/373
- pydanny/djangopackages/issues/374

**Comment by bashu** [comment]
can confirm, to reproduce try to add: https://github.com/bashu/django-permanent-helpers

**Comment by pydanny** [comment]
Okay, I get it. Things are broken. We'll look into it.

**Comment by wimglenn** [comment]
Is there any workaround for submitting packages while the main landing page UI is broken?

**Comment by agusmakmun** [comment]
Still doesn't work until this time.. :cry:

**Comment by pydanny** [comment]
I'm just starting again to work with the Django Software Foundation (DSF) to transfer the project to their ownership. 

In the meantime, please do not add any more "Me too's" or "Still doesn't work" comments. I know this is the case, and all related tickets will be addressed and closed in due time.
